from app.schemas import SourceConfigWrite


def default_source_configs() -> list[SourceConfigWrite]:
    return [
        SourceConfigWrite(
            name="GitHub 仓库",
            type="builtin",
            enabled=True,
            url_or_domain="github.com",
            language_hint="en",
            crawl_depth=1,
        ),
        SourceConfigWrite(
            name="掘金搜索",
            type="search_page",
            enabled=True,
            url_or_domain="https://juejin.cn/search?query={keyword}&type=0",
            language_hint="zh",
            crawl_depth=1,
        ),
        SourceConfigWrite(
            name="知乎搜索",
            type="search_page",
            enabled=True,
            url_or_domain="https://www.zhihu.com/search?type=content&q={keyword}",
            language_hint="zh",
            crawl_depth=1,
        ),
        SourceConfigWrite(
            name="少数派搜索",
            type="search_page",
            enabled=True,
            url_or_domain="https://sspai.com/search/post/{keyword}",
            language_hint="zh",
            crawl_depth=1,
        ),
        SourceConfigWrite(
            name="InfoQ 中文搜索",
            type="search_page",
            enabled=True,
            url_or_domain="https://www.infoq.cn/search?keyword={keyword}",
            language_hint="zh",
            crawl_depth=1,
        ),
        SourceConfigWrite(
            name="CSDN 搜索",
            type="search_page",
            enabled=True,
            url_or_domain="https://so.csdn.net/so/search?q={keyword}",
            language_hint="zh",
            crawl_depth=1,
        ),
        SourceConfigWrite(
            name="腾讯云开发者搜索",
            type="search_page",
            enabled=True,
            url_or_domain="https://cloud.tencent.com/developer/search/article-{keyword}",
            language_hint="zh",
            crawl_depth=1,
        ),
        SourceConfigWrite(
            name="Dev.to 搜索",
            type="search_page",
            enabled=True,
            url_or_domain="https://dev.to/search?q={keyword}",
            language_hint="en",
            crawl_depth=1,
        ),
        SourceConfigWrite(
            name="Stack Overflow 搜索",
            type="search_page",
            enabled=True,
            url_or_domain="https://stackoverflow.com/search?q={keyword}",
            language_hint="en",
            crawl_depth=1,
        ),
        SourceConfigWrite(
            name="Hacker News 搜索",
            type="search_page",
            enabled=True,
            url_or_domain="https://hn.algolia.com/?q={keyword}",
            language_hint="en",
            crawl_depth=1,
        ),
        SourceConfigWrite(
            name="Medium 搜索",
            type="search_page",
            enabled=True,
            url_or_domain="https://medium.com/search?q={keyword}",
            language_hint="en",
            crawl_depth=1,
        ),
        SourceConfigWrite(
            name="Reddit 搜索",
            type="search_page",
            enabled=True,
            url_or_domain="https://www.reddit.com/search/?q={keyword}",
            language_hint="en",
            crawl_depth=1,
        ),
        SourceConfigWrite(
            name="Google 新闻技术 RSS",
            type="rss",
            enabled=True,
            url_or_domain="https://news.google.com/rss/search?q={keyword}%20technology&hl=en-US&gl=US&ceid=US:en",
            language_hint="en",
            crawl_depth=1,
        ),
    ]
